# Generated by Django 3.0.5 on 2020-04-26 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0002_auto_20200426_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookitem',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shelf.Book'),
        ),
    ]
